'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Checkout
    Public Property CheckoutID As String
    Public Property ResourceID As String
    Public Property MemberID As String
    Public Property CheckOutDate As String
    Public Property ReturnDate As String

    Public Overridable Property Member As Member
    Public Overridable Property Resource As Resource

End Class
