'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Member
    Public Property MemberID As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property StreetAddress As String
    Public Property City As String
    Public Property State As String
    Public Property ZipCode As String
    Public Property Email As String
    Public Property Password As String

    Public Overridable Property Checkouts As ICollection(Of Checkout) = New HashSet(Of Checkout)

End Class
