'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Resource
    Public Property ResourceID As String
    Public Property Title As String
    Public Property AuthorLast As String
    Public Property AuthorFirst As String
    Public Property AuthorMiddle As String
    Public Property PublicationDate As String
    Public Property Series As String
    Public Property ISBN As String
    Public Property CheckOutPeriod As String
    Public Property Subject_1 As String
    Public Property Subject_2 As String
    Public Property BookInfo As String

    Public Overridable Property Checkouts As ICollection(Of Checkout) = New HashSet(Of Checkout)

End Class
